enableGlobalCache: false

npmRegistryServer: "https://artifactory.acorn.cirrostratus.org/artifactory/api/npm/npms/"

nodeLinker: pnp
cacheFolder: "./.yarn/cache"

supportedArchitectures: 
  os:
    - 'darwin'
    - 'linux'
  libc:
    - 'glibc'
    - 'musl'

yarnPath: .yarn/releases/yarn-4.6.0.cjs