approvedGitRepositories:
  - "**"

cacheFolder: ./.yarn/cache

enableGlobalCache: false

enableScripts: true

nodeLinker: node-modules

npmRegistryServer: "https://artifactory.acorn.cirrostratus.org/artifactory/api/npm/npms/"

supportedArchitectures:
  libc:
    - glibc
    - musl
  os:
    - darwin
    - linux

yarnPath: .yarn/releases/yarn-4.14.1.cjs
