include:
  - ".gitlab/deploy/_pipeline.yml"
  - project: capstan/pow/gitlab-templates
    file: /ephemeral-deployer/template.yml
    ref: ephemeral-deployer-v3
  - project: capstan/platform-apps/blueprint/glab-ci-link-to-build
    file: template.gitlab-ci.yml
    ref: "1"
    inputs:
      build_url: "https://$EUREKA_SERVICE_NAME.apps.$ENVIRONMENT.cirrostratus.org"
      build_link_text: "${APP_NAME} ephemeral deployment for commit ${CI_COMMIT_SHORT_SHA} for $USER_TYPE users"
      stage_name: notifications

deploy:
  stage: deploy
  extends: .ephemeral-deployer
  # workaround that will no longer be needed after https://jira.jstor.org/browse/POW-4382
  before_script:
    - export KUBECONFIG=$HOME/.kube/config
  variables:
    EKS_CLUSTER: ephemeral
    K8S_ACTION: apply
    MANIFEST_FILE: $MANIFEST_OUTPUT_DIRECTORY
  environment:
    name: $TARGET_CLUSTER-$API_TARGET
    url: https://$EUREKA_SERVICE_NAME.apps.$ENVIRONMENT.cirrostratus.org