// These imports and the registry are in alphabetical order, and for the sake of maintenance,
// it would probably be best to keep them that way.
import {
  PharosAlert,
  PharosButton,
  PharosCheckbox,
  PharosCheckboxGroup,
  PharosCombobox,
  PharosDropdownMenu,
  PharosDropdownMenuItem,
  PharosDropdownMenuNav,
  PharosDropdownMenuNavLink,
  PharosFooter,
  PharosHeader,
  PharosHeading,
  PharosIcon,
  PharosInputGroup,
  PharosLayout,
  PharosLink,
  PharosLoadingSpinner,
  PharosModal,
  PharosPagination,
  PharosRadioButton,
  PharosRadioGroup,
  PharosSelect,
  PharosSidenav,
  PharosSidenavButton,
  PharosSidenavLink,
  PharosSidenavMenu,
  PharosSidenavSection,
  PharosTab,
  PharosTabPanel,
  PharosTabs,
  PharosTextarea,
  PharosTextInput,
  PharosToast,
  PharosToaster,
  PharosToggleButton,
  PharosToggleButtonGroup,
  PharosTooltip
} from '@ithaka/pharos'

import registerComponents from '@ithaka/pharos/lib/utils/registerComponents'
export default {
  install() {
    registerComponents(`pep`, [
      PharosAlert,
      PharosButton,
      PharosCheckbox,
      PharosCheckboxGroup,
      PharosCombobox,
      PharosDropdownMenu,
      PharosDropdownMenuItem,
      PharosDropdownMenuNav,
      PharosDropdownMenuNavLink,
      PharosFooter,
      PharosHeader,
      PharosHeading,
      PharosIcon,
      PharosInputGroup,
      PharosLayout,
      PharosLink,
      PharosLoadingSpinner,
      PharosModal,
      PharosPagination,
      PharosRadioButton,
      PharosRadioGroup,
      PharosSelect,
      PharosSidenav,
      PharosSidenavButton,
      PharosSidenavLink,
      PharosSidenavMenu,
      PharosSidenavSection,
      PharosTab,
      PharosTabPanel,
      PharosTabs,
      PharosTextarea,
      PharosTextInput,
      PharosToast,
      PharosToaster,
      PharosToggleButton,
      PharosToggleButtonGroup,
      PharosTooltip
    ])
  }
}
